FROM ubuntu:latest
LABEL org.opencontainers.image.source=https://github.com/jwakely/pkg-gcc-latest
LABEL org.opencontainers.image.description="GCC snapshot in Ubuntu container"
LABEL org.opencontainers.image.licenses="GPL-3.0-or-later AND (GPL-3.0-or-later WITH GCC-exception-3.1) AND (Apache-2.0 WITH LLVM-exception)"
RUN apt-get update -y
RUN apt-get install -y build-essential wget
RUN wget --quiet --content-disposition http://kayari.org/gcc-latest/gcc-latest.deb
RUN dpkg -i gcc-latest*.deb
RUN /opt/gcc-latest/bin/g++ --version
