FROM fedora:latest
LABEL org.opencontainers.image.source=https://github.com/jwakely/pkg-gcc-latest
LABEL org.opencontainers.image.description="GCC snapshot in Fedora container"
LABEL org.opencontainers.image.licenses="GPL-3.0-or-later AND (GPL-3.0-or-later WITH GCC-exception-3.1) AND (Apache-2.0 WITH LLVM-exception)"
RUN dnf -y install 'dnf-command(copr)'
RUN dnf -y copr enable jwakely/gcc-latest
RUN dnf -y install gcc-latest
RUN /opt/gcc-latest/bin/g++ --version
